[broker]
command = "mads broker"
relaunch = true
tty=true

[feedback]
command = "mads feedback"
after = "broker"
tty = true

[perf_assess]
command = "mads perf_assess -p 100"
after = "broker"
tty=true
relaunch = true
scale = 2

